MODEL:
  TYPE: vit
  NAME: vit-b_16
  VIT:
    PATCH_SIZE: 16
    IN_CHANS: 3
    EMBED_DIM: 1024
    MLP_DIM: 4096
    DEPTH: 24
    HEADS: 16
    DIM_HEAD: 64
    POOL: 'cls'
    DROPOUT: 0.1
    EMB_DROPOUT: 0.0
