MODEL:
  TYPE: t2t-vit
  NAME: t2t-vit-12
  T2T_VIT:
    IN_CHANS: 3
    EMBED_DIM: 512
    # mlp_ratio = 3.
    MLP_DIM: 1536
    DEPTH: 24
    HEADS: 8
    DIM_HEAD: 64
    POOL: 'cls'
    DROPOUT: 0.1
    EMB_DROPOUT: 0.0
    TOKENS_TYPE: 'performer'
    T2T_LAYERS: ((7, 4), (3, 2), (3, 2))
