MODEL:
  TYPE: t2t-vit
  NAME: t2t-vit-12
  T2T_VIT:
    IN_CHANS: 3
    NUM_CLASSES: 1000
    DIM: 256
    MLP_DIM: 512
    DEPTH: 12
    HEADS: 4
    DIM_HEAD: 64
    POOL: 'cls'
    DROPOUT: 0.1
    EMB_DROPOUT: 0.0
    TOKENS_TYPE: 'performer'
    T2T_LAYERS: ((7, 4), (3, 2), (3, 2))
