MODEL:
  TYPE: swin
  NAME: swin_base_patch4_window7_224
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.5
  NUME_CLASSES: 1000
  RESUME: ''
  SWIN:
    PATCH_SIZE: 4
    IN_CHANS: 3
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
    MLP_RATIO: 4
    QKV_BIAS: True
    QK_SCALE: None
    APE: False
    PATCH_NORM: True